
//! Autogenerated weights for `pallet_trustless_agent`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2025-11-03, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: Some("thx-testnet"), DB CACHE: 1024

// Executed Command:
// ./target/release/thxnet-leafchain
// benchmark
// pallet
// --chain=thx-testnet
// --pallet=pallet_trustless_agent
// --extrinsic=*
// --steps=50
// --repeat=20
// --output=runtime/general/src/weights/pallet_trustless_agent.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_trustless_agent`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_trustless_agent::WeightInfo for WeightInfo<T> {
	/// Storage: TrustlessAgent NextAgentId (r:1 w:1)
	/// Proof: TrustlessAgent NextAgentId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent AgentsByOwner (r:1 w:1)
	/// Proof: TrustlessAgent AgentsByOwner (max_values: None, max_size: Some(8050), added: 10525, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent Agents (r:0 w:1)
	/// Proof: TrustlessAgent Agents (max_values: None, max_size: Some(574), added: 3049, mode: MaxEncodedLen)
	fn register_agent() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `80`
		//  Estimated: `13008`
		// Minimum execution time: 14_000_000 picoseconds.
		Weight::from_parts(14_000_000, 0)
			.saturating_add(Weight::from_parts(0, 13008))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: TrustlessAgent Agents (r:1 w:0)
	/// Proof: TrustlessAgent Agents (max_values: None, max_size: Some(574), added: 3049, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent AgentMetadata (r:0 w:1)
	/// Proof: TrustlessAgent AgentMetadata (max_values: None, max_size: Some(684), added: 3159, mode: MaxEncodedLen)
	fn update_metadata() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `331`
		//  Estimated: `4039`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4039))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: TrustlessAgent Agents (r:1 w:1)
	/// Proof: TrustlessAgent Agents (max_values: None, max_size: Some(574), added: 3049, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent AgentsByOwner (r:2 w:2)
	/// Proof: TrustlessAgent AgentsByOwner (max_values: None, max_size: Some(8050), added: 10525, mode: MaxEncodedLen)
	fn transfer_agent() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `480`
		//  Estimated: `29672`
		// Minimum execution time: 21_000_000 picoseconds.
		Weight::from_parts(22_000_000, 0)
			.saturating_add(Weight::from_parts(0, 29672))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: TrustlessAgent Agents (r:1 w:0)
	/// Proof: TrustlessAgent Agents (max_values: None, max_size: Some(574), added: 3049, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent AgentClientAuthorizations (r:1 w:0)
	/// Proof: TrustlessAgent AgentClientAuthorizations (max_values: None, max_size: Some(80), added: 2555, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent FeedbackAuthorizations (r:1 w:0)
	/// Proof: TrustlessAgent FeedbackAuthorizations (max_values: None, max_size: Some(77), added: 2552, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent FeedbackIndices (r:1 w:1)
	/// Proof: TrustlessAgent FeedbackIndices (max_values: None, max_size: Some(76), added: 2551, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent LastFeedbackTimestamp (r:1 w:1)
	/// Proof: TrustlessAgent LastFeedbackTimestamp (max_values: None, max_size: Some(76), added: 2551, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent NextFeedbackId (r:1 w:1)
	/// Proof: TrustlessAgent NextFeedbackId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent AgentFeedbacks (r:1 w:1)
	/// Proof: TrustlessAgent AgentFeedbacks (max_values: None, max_size: Some(80026), added: 82501, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent ClientFeedbacks (r:1 w:1)
	/// Proof: TrustlessAgent ClientFeedbacks (max_values: None, max_size: Some(8050), added: 10525, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent AgentValidations (r:1 w:0)
	/// Proof: TrustlessAgent AgentValidations (max_values: None, max_size: Some(826), added: 3301, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent Feedbacks (r:0 w:1)
	/// Proof: TrustlessAgent Feedbacks (max_values: None, max_size: Some(1937), added: 4412, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent AgentReputations (r:0 w:1)
	/// Proof: TrustlessAgent AgentReputations (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	fn give_feedback() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `451`
		//  Estimated: `118998`
		// Minimum execution time: 31_000_000 picoseconds.
		Weight::from_parts(32_000_000, 0)
			.saturating_add(Weight::from_parts(0, 118998))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: TrustlessAgent Feedbacks (r:1 w:1)
	/// Proof: TrustlessAgent Feedbacks (max_values: None, max_size: Some(1937), added: 4412, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent AgentFeedbacks (r:1 w:0)
	/// Proof: TrustlessAgent AgentFeedbacks (max_values: None, max_size: Some(80026), added: 82501, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent AgentValidations (r:1 w:0)
	/// Proof: TrustlessAgent AgentValidations (max_values: None, max_size: Some(826), added: 3301, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent AgentReputations (r:0 w:1)
	/// Proof: TrustlessAgent AgentReputations (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	fn revoke_feedback() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `667`
		//  Estimated: `93184`
		// Minimum execution time: 21_000_000 picoseconds.
		Weight::from_parts(22_000_000, 0)
			.saturating_add(Weight::from_parts(0, 93184))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: TrustlessAgent Feedbacks (r:1 w:0)
	/// Proof: TrustlessAgent Feedbacks (max_values: None, max_size: Some(1937), added: 4412, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent Agents (r:1 w:0)
	/// Proof: TrustlessAgent Agents (max_values: None, max_size: Some(574), added: 3049, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent FeedbackResponses (r:1 w:1)
	/// Proof: TrustlessAgent FeedbackResponses (max_values: None, max_size: Some(11025), added: 13500, mode: MaxEncodedLen)
	fn append_response() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `799`
		//  Estimated: `23931`
		// Minimum execution time: 14_000_000 picoseconds.
		Weight::from_parts(15_000_000, 0)
			.saturating_add(Weight::from_parts(0, 23931))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: TrustlessAgent Validators (r:1 w:1)
	/// Proof: TrustlessAgent Validators (max_values: None, max_size: Some(101), added: 2576, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent ValidatorWhitelist (r:1 w:0)
	/// Proof: TrustlessAgent ValidatorWhitelist (max_values: None, max_size: Some(49), added: 2524, mode: MaxEncodedLen)
	fn register_validator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `80`
		//  Estimated: `7080`
		// Minimum execution time: 14_000_000 picoseconds.
		Weight::from_parts(14_000_000, 0)
			.saturating_add(Weight::from_parts(0, 7080))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: TrustlessAgent Validators (r:1 w:1)
	/// Proof: TrustlessAgent Validators (max_values: None, max_size: Some(101), added: 2576, mode: MaxEncodedLen)
	fn unregister_validator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `209`
		//  Estimated: `3566`
		// Minimum execution time: 13_000_000 picoseconds.
		Weight::from_parts(14_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3566))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: TrustlessAgent Agents (r:1 w:0)
	/// Proof: TrustlessAgent Agents (max_values: None, max_size: Some(574), added: 3049, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent NextRequestId (r:1 w:1)
	/// Proof: TrustlessAgent NextRequestId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent AgentValidations (r:1 w:1)
	/// Proof: TrustlessAgent AgentValidations (max_values: None, max_size: Some(826), added: 3301, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent ValidationRequests (r:0 w:1)
	/// Proof: TrustlessAgent ValidationRequests (max_values: None, max_size: Some(89), added: 2564, mode: MaxEncodedLen)
	fn request_validation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `222`
		//  Estimated: `9823`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(16_000_000, 0)
			.saturating_add(Weight::from_parts(0, 9823))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: TrustlessAgent ValidationRequests (r:1 w:1)
	/// Proof: TrustlessAgent ValidationRequests (max_values: None, max_size: Some(89), added: 2564, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent Validators (r:1 w:0)
	/// Proof: TrustlessAgent Validators (max_values: None, max_size: Some(101), added: 2576, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent ValidationResponses (r:2 w:1)
	/// Proof: TrustlessAgent ValidationResponses (max_values: None, max_size: Some(1984), added: 4459, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent AgentFeedbacks (r:1 w:0)
	/// Proof: TrustlessAgent AgentFeedbacks (max_values: None, max_size: Some(80026), added: 82501, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent AgentValidations (r:1 w:0)
	/// Proof: TrustlessAgent AgentValidations (max_values: None, max_size: Some(826), added: 3301, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent AgentReputations (r:0 w:1)
	/// Proof: TrustlessAgent AgentReputations (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	fn submit_validation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `604`
		//  Estimated: `108403`
		// Minimum execution time: 36_000_000 picoseconds.
		Weight::from_parts(37_000_000, 0)
			.saturating_add(Weight::from_parts(0, 108403))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: TrustlessAgent Agents (r:1 w:0)
	/// Proof: TrustlessAgent Agents (max_values: None, max_size: Some(574), added: 3049, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent NextEscrowId (r:1 w:1)
	/// Proof: TrustlessAgent NextEscrowId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent Escrows (r:0 w:1)
	/// Proof: TrustlessAgent Escrows (max_values: None, max_size: Some(93), added: 2568, mode: MaxEncodedLen)
	fn create_escrow() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `268`
		//  Estimated: `5532`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(16_000_000, 0)
			.saturating_add(Weight::from_parts(0, 5532))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: TrustlessAgent Escrows (r:1 w:1)
	/// Proof: TrustlessAgent Escrows (max_values: None, max_size: Some(93), added: 2568, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent Agents (r:1 w:0)
	/// Proof: TrustlessAgent Agents (max_values: None, max_size: Some(574), added: 3049, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn claim_escrow() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `551`
		//  Estimated: `11190`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(26_000_000, 0)
			.saturating_add(Weight::from_parts(0, 11190))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: TrustlessAgent Escrows (r:1 w:1)
	/// Proof: TrustlessAgent Escrows (max_values: None, max_size: Some(93), added: 2568, mode: MaxEncodedLen)
	fn cancel_escrow() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `295`
		//  Estimated: `3558`
		// Minimum execution time: 14_000_000 picoseconds.
		Weight::from_parts(14_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3558))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: TrustlessAgent ValidationRequests (r:1 w:1)
	/// Proof: TrustlessAgent ValidationRequests (max_values: None, max_size: Some(89), added: 2564, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent AgentValidations (r:1 w:1)
	/// Proof: TrustlessAgent AgentValidations (max_values: None, max_size: Some(826), added: 3301, mode: MaxEncodedLen)
	fn cancel_validation_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `376`
		//  Estimated: `7845`
		// Minimum execution time: 17_000_000 picoseconds.
		Weight::from_parts(18_000_000, 0)
			.saturating_add(Weight::from_parts(0, 7845))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: TrustlessAgent Feedbacks (r:1 w:0)
	/// Proof: TrustlessAgent Feedbacks (max_values: None, max_size: Some(1937), added: 4412, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent Agents (r:1 w:0)
	/// Proof: TrustlessAgent Agents (max_values: None, max_size: Some(574), added: 3049, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent NextDisputeId (r:1 w:1)
	/// Proof: TrustlessAgent NextDisputeId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent FeedbackDisputes (r:1 w:1)
	/// Proof: TrustlessAgent FeedbackDisputes (max_values: None, max_size: Some(105), added: 2580, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent Disputes (r:0 w:1)
	/// Proof: TrustlessAgent Disputes (max_values: None, max_size: Some(620), added: 3095, mode: MaxEncodedLen)
	fn dispute_feedback() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `868`
		//  Estimated: `14504`
		// Minimum execution time: 21_000_000 picoseconds.
		Weight::from_parts(22_000_000, 0)
			.saturating_add(Weight::from_parts(0, 14504))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: TrustlessAgent Disputes (r:1 w:1)
	/// Proof: TrustlessAgent Disputes (max_values: None, max_size: Some(620), added: 3095, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent Feedbacks (r:1 w:1)
	/// Proof: TrustlessAgent Feedbacks (max_values: None, max_size: Some(1937), added: 4412, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent AgentFeedbacks (r:1 w:0)
	/// Proof: TrustlessAgent AgentFeedbacks (max_values: None, max_size: Some(80026), added: 82501, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent AgentValidations (r:1 w:0)
	/// Proof: TrustlessAgent AgentValidations (max_values: None, max_size: Some(826), added: 3301, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: TrustlessAgent AgentReputations (r:0 w:1)
	/// Proof: TrustlessAgent AgentReputations (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	fn resolve_dispute() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1025`
		//  Estimated: `100862`
		// Minimum execution time: 27_000_000 picoseconds.
		Weight::from_parts(28_000_000, 0)
			.saturating_add(Weight::from_parts(0, 100862))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: TrustlessAgent ValidatorWhitelist (r:1 w:1)
	/// Proof: TrustlessAgent ValidatorWhitelist (max_values: None, max_size: Some(49), added: 2524, mode: MaxEncodedLen)
	fn add_validator_to_whitelist() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `80`
		//  Estimated: `3514`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(7_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3514))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: TrustlessAgent ValidatorWhitelist (r:1 w:1)
	/// Proof: TrustlessAgent ValidatorWhitelist (max_values: None, max_size: Some(49), added: 2524, mode: MaxEncodedLen)
	fn remove_validator_from_whitelist() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `155`
		//  Estimated: `3514`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(9_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3514))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
