//! Autogenerated weights for `pallet_rwa`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2026-03-16, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Noels-MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("thx-testnet"), DB CACHE: 1024

// Executed Command:
// ./target/release/thxnet-leafchain
// benchmark
// pallet
// --chain
// thx-testnet
// --pallet
// pallet_rwa
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/rwa/src/weights.rs
// --execution
// wasm
// --wasm-execution
// compiled

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

pub trait WeightInfo {
    fn register_asset() -> Weight;
    fn update_asset_policy() -> Weight;
    fn deactivate_asset() -> Weight;
    fn reactivate_asset() -> Weight;
    fn sunset_asset() -> Weight;
    fn force_retire_asset() -> Weight;
    fn retire_asset() -> Weight;
    fn request_participation() -> Weight;
    fn approve_participation() -> Weight;
    fn reject_participation() -> Weight;
    fn exit_participation() -> Weight;
    fn renew_participation() -> Weight;
    fn settle_expired_participation() -> Weight;
    fn claim_retired_deposit() -> Weight;
    fn add_holder() -> Weight;
    fn remove_holder() -> Weight;
    fn leave_participation() -> Weight;
    fn set_slash_distribution() -> Weight;
    fn slash_participation() -> Weight;
    fn revoke_participation() -> Weight;
    fn transfer_ownership() -> Weight;
    fn accept_ownership() -> Weight;
    fn cancel_ownership_transfer() -> Weight;
    fn update_beneficiary() -> Weight;
    fn update_metadata() -> Weight;
    fn transfer_participation() -> Weight;
    fn pause_asset() -> Weight;
    fn unpause_asset() -> Weight;
    fn batch_reject_pending() -> Weight;
}

/// Weight functions for `pallet_rwa`.
///
/// Values below were generated by running frame-benchmarking CLI on local hardware
/// (Apple Silicon, aarch64). For production, re-benchmark on reference hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: Rwa OwnerAssets (r:1 w:1)
    /// Storage: System Account (r:1 w:1)
    /// Storage: Rwa NextRwaAssetId (r:1 w:1)
    /// Storage: Rwa RwaAssets (r:0 w:1)
    /// Component `m` range: [0, 256]. Worst-case used here (m=256).
    fn register_asset() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `57`
        //  Estimated: `8997`
        // Minimum execution time: 25_000 nanoseconds.
        Weight::from_parts(27_279_199, 8997)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(4))
    }

    /// Storage: Rwa RwaAssets (r:1 w:1)
    fn update_asset_policy() -> Weight {
        // Measured:  `246`
        // Estimated: `3884`
        // Minimum execution time: 12_000 nanoseconds.
        Weight::from_parts(13_000_000, 3884)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: Rwa RwaAssets (r:1 w:1)
    fn deactivate_asset() -> Weight {
        // Measured:  `246`
        // Estimated: `3884`
        // Minimum execution time: 12_000 nanoseconds.
        Weight::from_parts(13_000_000, 3884)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: Rwa RwaAssets (r:1 w:1)
    fn reactivate_asset() -> Weight {
        // Measured:  `246`
        // Estimated: `3884`
        // Minimum execution time: 12_000 nanoseconds.
        Weight::from_parts(13_000_000, 3884)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: Rwa SunsettingAssets (r:1 w:1)
    /// Storage: Rwa RwaAssets (r:1 w:1)
    fn sunset_asset() -> Weight {
        // Measured:  `288`
        // Estimated: `7570`
        // Minimum execution time: 17_000 nanoseconds.
        Weight::from_parts(18_000_000, 7570)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    /// Storage: Rwa RwaAssets (r:1 w:1)
    /// Storage: Crowdfunding Campaigns (r:1 w:0) -- lifecycle guard
    /// Storage: System Account (r:1 w:1)
    /// Storage: Rwa OwnerAssets (r:1 w:1)
    /// Storage: Rwa PendingApprovals (r:0 w:1)
    /// Storage: Rwa PendingOwnershipTransfer (r:0 w:1)
    /// Storage: Rwa AssetSlashDistribution (r:0 w:1)
    fn force_retire_asset() -> Weight {
        // Measured:  `349`
        // Estimated: `16472`
        // Minimum execution time: 34_000 nanoseconds.
        Weight::from_parts(35_000_000, 16472)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(6))
    }

    /// Storage: Rwa RwaAssets (r:1 w:1)
    /// Storage: System Account (r:1 w:1)
    /// Storage: Rwa OwnerAssets (r:1 w:1)
    /// Storage: Rwa SunsettingAssets (r:1 w:1)
    /// Storage: Rwa PendingApprovals (r:0 w:1)
    /// Storage: Rwa PendingOwnershipTransfer (r:0 w:1)
    /// Storage: Rwa AssetSlashDistribution (r:0 w:1)
    fn retire_asset() -> Weight {
        // Measured:  `392`
        // Estimated: `15078`
        // Minimum execution time: 35_000 nanoseconds.
        Weight::from_parts(35_000_000, 15078)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(7))
    }

    /// Storage: Rwa RwaAssets (r:1 w:1)
    /// Storage: Rwa HolderIndex (r:h w:h)
    /// Storage: Rwa HolderAssets (r:h w:h)
    /// Storage: System Account (r:2 w:2)
    /// Storage: Rwa NextParticipationId (r:1 w:1)
    /// Storage: Rwa Participations (r:0 w:1)
    /// Component `h` range: [1, 10]. Worst-case used here (h=10).
    fn request_participation() -> Weight {
        // Measured:  `494`
        // Estimated: `15549 + h * 5271`
        // Minimum execution time: 48_000 nanoseconds (h=1).
        // Worst case (h=10): ~112_000 nanoseconds.
        Weight::from_parts(111_793_196, 68259)
            .saturating_add(T::DbWeight::get().reads(24))
            .saturating_add(T::DbWeight::get().writes(25))
    }

    /// Storage: Rwa RwaAssets (r:1 w:0)
    /// Storage: Rwa Participations (r:1 w:1)
    /// Storage: Rwa PendingApprovals (r:1 w:1)
    fn approve_participation() -> Weight {
        // Measured:  `531`
        // Estimated: `11675`
        // Minimum execution time: 24_000 nanoseconds.
        Weight::from_parts(26_000_000, 11675)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    /// Storage: Rwa RwaAssets (r:1 w:1)
    /// Storage: Rwa Participations (r:1 w:1)
    /// Storage: System Account (r:2 w:2)
    /// Storage: Rwa HolderAssets (r:1 w:1)
    /// Storage: Rwa PendingApprovals (r:1 w:1)
    /// Storage: Rwa HolderIndex (r:0 w:1)
    fn reject_participation() -> Weight {
        // Measured:  `816`
        // Estimated: `21585`
        // Minimum execution time: 48_000 nanoseconds.
        Weight::from_parts(48_000_000, 21585)
            .saturating_add(T::DbWeight::get().reads(6))
            .saturating_add(T::DbWeight::get().writes(7))
    }

    /// Storage: Rwa Participations (r:1 w:1)
    /// Storage: Rwa RwaAssets (r:1 w:1)
    /// Storage: System Account (r:2 w:2)
    /// Storage: Rwa HolderAssets (r:1 w:1)
    /// Storage: Rwa HolderIndex (r:0 w:1)
    fn exit_participation() -> Weight {
        // Measured:  `772`
        // Estimated: `17698`
        // Minimum execution time: 42_000 nanoseconds.
        Weight::from_parts(43_000_000, 17698)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(6))
    }

    /// Storage: Rwa RwaAssets (r:1 w:0)
    /// Storage: Rwa Participations (r:1 w:1)
    fn renew_participation() -> Weight {
        // Measured:  `487`
        // Estimated: `7788`
        // Minimum execution time: 19_000 nanoseconds.
        Weight::from_parts(20_000_000, 7788)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: Rwa RwaAssets (r:1 w:1)
    /// Storage: Rwa Participations (r:1 w:1)
    /// Storage: System Account (r:2 w:2)
    /// Storage: Rwa HolderAssets (r:1 w:1)
    /// Storage: Rwa HolderIndex (r:0 w:1)
    fn settle_expired_participation() -> Weight {
        // Measured:  `780`
        // Estimated: `17698`
        // Minimum execution time: 42_000 nanoseconds.
        Weight::from_parts(43_000_000, 17698)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(6))
    }

    /// Storage: Rwa RwaAssets (r:1 w:1)
    /// Storage: Rwa Participations (r:1 w:1)
    /// Storage: System Account (r:2 w:2)
    /// Storage: Rwa HolderAssets (r:1 w:1)
    /// Storage: Rwa HolderIndex (r:0 w:1)
    fn claim_retired_deposit() -> Weight {
        // Measured:  `772`
        // Estimated: `17698`
        // Minimum execution time: 43_000 nanoseconds.
        Weight::from_parts(43_000_000, 17698)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(6))
    }

    /// Storage: Rwa RwaAssets (r:1 w:0)
    /// Storage: Rwa Participations (r:1 w:1)
    /// Storage: Rwa HolderIndex (r:1 w:1)
    /// Storage: Rwa HolderAssets (r:1 w:1)
    fn add_holder() -> Weight {
        // Measured:  `627`
        // Estimated: `15039`
        // Minimum execution time: 26_000 nanoseconds.
        Weight::from_parts(27_000_000, 15039)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    /// Storage: Rwa RwaAssets (r:1 w:0)
    /// Storage: Rwa Participations (r:1 w:1)
    /// Storage: Rwa HolderAssets (r:1 w:1)
    /// Storage: Rwa HolderIndex (r:0 w:1)
    fn remove_holder() -> Weight {
        // Measured:  `635`
        // Estimated: `11502`
        // Minimum execution time: 24_000 nanoseconds.
        Weight::from_parts(25_000_000, 11502)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    /// Storage: Rwa RwaAssets (r:1 w:0)
    /// Storage: Rwa Participations (r:1 w:1)
    /// Storage: Rwa HolderAssets (r:1 w:1)
    /// Storage: Rwa HolderIndex (r:0 w:1)
    fn leave_participation() -> Weight {
        // Measured:  `635`
        // Estimated: `11502`
        // Minimum execution time: 24_000 nanoseconds.
        Weight::from_parts(24_000_000, 11502)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    /// Storage: Rwa RwaAssets (r:1 w:0)
    /// Storage: Rwa AssetSlashDistribution (r:0 w:1)
    fn set_slash_distribution() -> Weight {
        // Measured:  `246`
        // Estimated: `3884`
        // Minimum execution time: 13_000 nanoseconds.
        Weight::from_parts(14_000_000, 3884)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: Rwa RwaAssets (r:1 w:1)
    /// Storage: Rwa Participations (r:1 w:1)
    /// Storage: Crowdfunding Campaigns (r:1 w:0) -- lifecycle guard
    /// Storage: Rwa AssetSlashDistribution (r:1 w:0)
    /// Storage: System Account (r:3 w:3)
    /// Storage: Rwa HolderAssets (r:1 w:1)
    /// Storage: Rwa HolderIndex (r:0 w:1)
    fn slash_participation() -> Weight {
        // Measured:  `885`
        // Estimated: `29052`
        // Minimum execution time: 62_000 nanoseconds.
        Weight::from_parts(63_000_000, 29052)
            .saturating_add(T::DbWeight::get().reads(8))
            .saturating_add(T::DbWeight::get().writes(7))
    }

    /// Storage: Rwa RwaAssets (r:1 w:1)
    /// Storage: Rwa Participations (r:1 w:1)
    /// Storage: System Account (r:2 w:2)
    /// Storage: Rwa HolderAssets (r:1 w:1)
    /// Storage: Rwa HolderIndex (r:0 w:1)
    fn revoke_participation() -> Weight {
        // Measured:  `772`
        // Estimated: `17698`
        // Minimum execution time: 42_000 nanoseconds.
        Weight::from_parts(43_000_000, 17698)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(6))
    }

    /// Storage: Rwa RwaAssets (r:1 w:0)
    /// Storage: Rwa PendingOwnershipTransfer (r:0 w:1)
    fn transfer_ownership() -> Weight {
        // Measured:  `246`
        // Estimated: `3884`
        // Minimum execution time: 13_000 nanoseconds.
        Weight::from_parts(13_000_000, 3884)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: Rwa PendingOwnershipTransfer (r:1 w:1)
    /// Storage: Rwa RwaAssets (r:1 w:1)
    /// Storage: Rwa OwnerAssets (r:2 w:2)
    /// Storage: System Account (r:2 w:2)
    fn accept_ownership() -> Weight {
        // Measured:  `555`
        // Estimated: `20437`
        // Minimum execution time: 45_000 nanoseconds.
        Weight::from_parts(46_000_000, 20437)
            .saturating_add(T::DbWeight::get().reads(6))
            .saturating_add(T::DbWeight::get().writes(6))
    }

    /// Storage: Rwa RwaAssets (r:1 w:0)
    /// Storage: Rwa PendingOwnershipTransfer (r:1 w:1)
    fn cancel_ownership_transfer() -> Weight {
        // Measured:  `323`
        // Estimated: `7401`
        // Minimum execution time: 15_000 nanoseconds.
        Weight::from_parts(16_000_000, 7401)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: Rwa RwaAssets (r:1 w:1)
    fn update_beneficiary() -> Weight {
        // Measured:  `246`
        // Estimated: `3884`
        // Minimum execution time: 14_000 nanoseconds.
        Weight::from_parts(15_000_000, 3884)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: Rwa RwaAssets (r:1 w:1)
    fn update_metadata() -> Weight {
        // Measured:  `246`
        // Estimated: `3884`
        // Minimum execution time: 15_000 nanoseconds.
        Weight::from_parts(15_000_000, 3884)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: Rwa RwaAssets (r:1 w:0)
    /// Storage: Rwa Participations (r:1 w:1)
    fn transfer_participation() -> Weight {
        // Measured:  `487`
        // Estimated: `7788`
        // Minimum execution time: 16_000 nanoseconds.
        Weight::from_parts(17_000_000, 7788)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: Rwa RwaAssets (r:1 w:1)
    fn pause_asset() -> Weight {
        // Measured:  `246`
        // Estimated: `3884`
        // Minimum execution time: 12_000 nanoseconds.
        Weight::from_parts(13_000_000, 3884)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: Rwa RwaAssets (r:1 w:1)
    fn unpause_asset() -> Weight {
        // Measured:  `246`
        // Estimated: `3884`
        // Minimum execution time: 12_000 nanoseconds.
        Weight::from_parts(13_000_000, 3884)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: Rwa RwaAssets (r:1 w:1)
    /// Storage: Rwa PendingApprovals (r:1 w:1)
    /// Storage: Rwa Participations (r:n w:n)
    /// Storage: System Account (r:n+1 w:n+1)
    /// Storage: Rwa HolderAssets (r:n w:n)
    /// Storage: Rwa HolderIndex (r:0 w:n)
    /// Component `n` range: [1, 100]. Worst-case used here (n=100).
    fn batch_reject_pending() -> Weight {
        // Measured:  `309 + n * 355`
        // Estimated: `13344 + n * 8241`
        // Minimum execution time: 48_000 nanoseconds (n=1).
        // Worst case (n=100): ~2_906_000 nanoseconds.
        Weight::from_parts(2_906_500_000, 837444)
            .saturating_add(T::DbWeight::get().reads(303))
            .saturating_add(T::DbWeight::get().writes(403))
    }
}

/// Fallback weights for testing / development.
impl WeightInfo for () {
    fn register_asset() -> Weight {
        Weight::from_parts(27_279_199, 8997)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(4))
    }

    fn update_asset_policy() -> Weight {
        Weight::from_parts(13_000_000, 3884)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    fn deactivate_asset() -> Weight {
        Weight::from_parts(13_000_000, 3884)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    fn reactivate_asset() -> Weight {
        Weight::from_parts(13_000_000, 3884)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    fn sunset_asset() -> Weight {
        Weight::from_parts(18_000_000, 7570)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }

    fn force_retire_asset() -> Weight {
        Weight::from_parts(35_000_000, 16472)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(6))
    }

    fn retire_asset() -> Weight {
        Weight::from_parts(35_000_000, 15078)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(7))
    }

    fn request_participation() -> Weight {
        Weight::from_parts(111_793_196, 68259)
            .saturating_add(RocksDbWeight::get().reads(24))
            .saturating_add(RocksDbWeight::get().writes(25))
    }

    fn approve_participation() -> Weight {
        Weight::from_parts(26_000_000, 11675)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(2))
    }

    fn reject_participation() -> Weight {
        Weight::from_parts(48_000_000, 21585)
            .saturating_add(RocksDbWeight::get().reads(6))
            .saturating_add(RocksDbWeight::get().writes(7))
    }

    fn exit_participation() -> Weight {
        Weight::from_parts(43_000_000, 17698)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(6))
    }

    fn renew_participation() -> Weight {
        Weight::from_parts(20_000_000, 7788)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    fn settle_expired_participation() -> Weight {
        Weight::from_parts(43_000_000, 17698)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(6))
    }

    fn claim_retired_deposit() -> Weight {
        Weight::from_parts(43_000_000, 17698)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(6))
    }

    fn add_holder() -> Weight {
        Weight::from_parts(27_000_000, 15039)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(3))
    }

    fn remove_holder() -> Weight {
        Weight::from_parts(25_000_000, 11502)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(3))
    }

    fn leave_participation() -> Weight {
        Weight::from_parts(24_000_000, 11502)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(3))
    }

    fn set_slash_distribution() -> Weight {
        Weight::from_parts(14_000_000, 3884)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    fn slash_participation() -> Weight {
        Weight::from_parts(63_000_000, 29052)
            .saturating_add(RocksDbWeight::get().reads(8))
            .saturating_add(RocksDbWeight::get().writes(7))
    }

    fn revoke_participation() -> Weight {
        Weight::from_parts(43_000_000, 17698)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(6))
    }

    fn transfer_ownership() -> Weight {
        Weight::from_parts(13_000_000, 3884)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    fn accept_ownership() -> Weight {
        Weight::from_parts(46_000_000, 20437)
            .saturating_add(RocksDbWeight::get().reads(6))
            .saturating_add(RocksDbWeight::get().writes(6))
    }

    fn cancel_ownership_transfer() -> Weight {
        Weight::from_parts(16_000_000, 7401)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    fn update_beneficiary() -> Weight {
        Weight::from_parts(15_000_000, 3884)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    fn update_metadata() -> Weight {
        Weight::from_parts(15_000_000, 3884)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    fn transfer_participation() -> Weight {
        Weight::from_parts(17_000_000, 7788)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    fn pause_asset() -> Weight {
        Weight::from_parts(13_000_000, 3884)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    fn unpause_asset() -> Weight {
        Weight::from_parts(13_000_000, 3884)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    fn batch_reject_pending() -> Weight {
        Weight::from_parts(2_906_500_000, 837444)
            .saturating_add(RocksDbWeight::get().reads(303))
            .saturating_add(RocksDbWeight::get().writes(403))
    }
}
