//! Autogenerated weights for `pallet_crowdfunding`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2026-03-16, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Noels-MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("thx-testnet"), DB CACHE: 1024

// Executed Command:
// ./target/release/thxnet-leafchain
// benchmark
// pallet
// --chain
// thx-testnet
// --pallet
// pallet_crowdfunding
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/crowdfunding/src/weights.rs
// --execution
// wasm
// --wasm-execution
// compiled

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

pub trait WeightInfo {
    fn create_campaign() -> Weight;
    fn cancel_campaign() -> Weight;
    fn set_default_eligibility() -> Weight;
    fn invest() -> Weight;
    fn withdraw_investment() -> Weight;
    fn claim_refund() -> Weight;
    fn finalize_campaign() -> Weight;
    fn claim_funds() -> Weight;
    fn claim_creation_deposit() -> Weight;
    fn submit_milestone() -> Weight;
    fn approve_milestone() -> Weight;
    fn reject_milestone() -> Weight;
    fn claim_milestone_funds() -> Weight;
    fn pause_campaign() -> Weight;
    fn resume_campaign() -> Weight;
    fn add_to_whitelist() -> Weight;
    fn remove_from_whitelist() -> Weight;
    fn set_protocol_config() -> Weight;
    fn report_license_revoked() -> Weight;
}

/// Weight functions for `pallet_crowdfunding`.
///
/// Values below were generated by running frame-benchmarking CLI on local hardware
/// (Apple Silicon, aarch64). For production, re-benchmark on reference hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: Crowdfunding CreatorCampaigns (r:1 w:1)
    /// Storage: Crowdfunding NextCampaignId (r:1 w:1)
    /// Storage: System Account (r:1 w:1)
    /// Storage: Crowdfunding DefaultEligibilityRules (r:1 w:0)
    /// Storage: Crowdfunding ProtocolFeeBpsOverride (r:1 w:0)
    /// Storage: Crowdfunding Campaigns (r:0 w:1)
    fn create_campaign() -> Weight {
        // Measured:  `4`
        // Estimated: `12684`
        // Minimum execution time: 42_000 nanoseconds.
        Weight::from_parts(42_000_000, 12684)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(4))
    }

    /// Storage: Crowdfunding Campaigns (r:1 w:1)
    /// Storage: Crowdfunding CampaignWhitelistCount (r:0 w:1)
    fn cancel_campaign() -> Weight {
        // Measured:  `262`
        // Estimated: `5080`
        // Minimum execution time: 17_000 nanoseconds.
        Weight::from_parts(17_000_000, 5080)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    /// Storage: Crowdfunding DefaultEligibilityRules (r:0 w:1)
    fn set_default_eligibility() -> Weight {
        // Measured:  `0`
        // Estimated: `0`
        // Minimum execution time: 7_000 nanoseconds.
        Weight::from_parts(8_000_000, 0)
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: Crowdfunding Campaigns (r:1 w:1)
    /// Storage: Crowdfunding Investments (r:1 w:1)
    /// Storage: Crowdfunding InvestorCampaigns (r:1 w:1)
    /// Storage: System Account (r:2 w:2)
    fn invest() -> Weight {
        // Measured:  `505`
        // Estimated: `18555`
        // Minimum execution time: 41_000 nanoseconds.
        Weight::from_parts(43_000_000, 18555)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(5))
    }

    /// Storage: Crowdfunding Campaigns (r:1 w:1)
    /// Storage: Crowdfunding Investments (r:1 w:1)
    /// Storage: System Account (r:2 w:2)
    fn withdraw_investment() -> Weight {
        // Measured:  `660`
        // Estimated: `14841`
        // Minimum execution time: 48_000 nanoseconds.
        Weight::from_parts(50_000_000, 14841)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(4))
    }

    /// Storage: Crowdfunding Campaigns (r:1 w:1)
    /// Storage: Crowdfunding Investments (r:1 w:1)
    /// Storage: System Account (r:2 w:2)
    /// Storage: Crowdfunding InvestorCampaigns (r:1 w:1)
    fn claim_refund() -> Weight {
        // Measured:  `702`
        // Estimated: `18555`
        // Minimum execution time: 41_000 nanoseconds.
        Weight::from_parts(42_000_000, 18555)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(5))
    }

    /// Storage: Crowdfunding Campaigns (r:1 w:1)
    fn finalize_campaign() -> Weight {
        // Measured:  `328`
        // Estimated: `5080`
        // Minimum execution time: 13_000 nanoseconds.
        Weight::from_parts(15_000_000, 5080)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: Crowdfunding Campaigns (r:1 w:1)
    /// Storage: Crowdfunding ProtocolFeeRecipientOverride (r:1 w:0)
    /// Storage: System Account (r:2 w:2)
    fn claim_funds() -> Weight {
        // Measured:  `431`
        // Estimated: `12793`
        // Minimum execution time: 59_000 nanoseconds.
        Weight::from_parts(61_000_000, 12793)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    /// Storage: Crowdfunding Campaigns (r:1 w:1)
    /// Storage: System Account (r:1 w:1)
    /// Storage: Crowdfunding CreatorCampaigns (r:1 w:1)
    /// Storage: Crowdfunding CampaignWhitelistCount (r:0 w:1)
    fn claim_creation_deposit() -> Weight {
        // Measured:  `407`
        // Estimated: `12267`
        // Minimum execution time: 41_000 nanoseconds.
        Weight::from_parts(42_000_000, 12267)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(4))
    }

    /// Storage: Crowdfunding Campaigns (r:1 w:0)
    /// Storage: Crowdfunding MilestoneStatuses (r:1 w:1)
    fn submit_milestone() -> Weight {
        // Measured:  `486`
        // Estimated: `8583`
        // Minimum execution time: 16_000 nanoseconds.
        Weight::from_parts(17_000_000, 8583)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: Crowdfunding Campaigns (r:1 w:0)
    /// Storage: Crowdfunding MilestoneStatuses (r:1 w:1)
    fn approve_milestone() -> Weight {
        // Measured:  `486`
        // Estimated: `8583`
        // Minimum execution time: 16_000 nanoseconds.
        Weight::from_parts(17_000_000, 8583)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: Crowdfunding Campaigns (r:1 w:0)
    /// Storage: Crowdfunding MilestoneStatuses (r:1 w:1)
    fn reject_milestone() -> Weight {
        // Measured:  `486`
        // Estimated: `8583`
        // Minimum execution time: 15_000 nanoseconds.
        Weight::from_parts(17_000_000, 8583)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: Crowdfunding Campaigns (r:1 w:1)
    /// Storage: Crowdfunding MilestoneStatuses (r:2 w:1)
    /// Storage: Crowdfunding ProtocolFeeRecipientOverride (r:1 w:0)
    /// Storage: System Account (r:2 w:2)
    fn claim_milestone_funds() -> Weight {
        // Measured:  `589`
        // Estimated: `18809`
        // Minimum execution time: 69_000 nanoseconds.
        Weight::from_parts(72_000_000, 18809)
            .saturating_add(T::DbWeight::get().reads(6))
            .saturating_add(T::DbWeight::get().writes(4))
    }

    /// Storage: Crowdfunding Campaigns (r:1 w:1)
    fn pause_campaign() -> Weight {
        // Measured:  `262`
        // Estimated: `5080`
        // Minimum execution time: 13_000 nanoseconds.
        Weight::from_parts(14_000_000, 5080)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: Crowdfunding Campaigns (r:1 w:1)
    fn resume_campaign() -> Weight {
        // Measured:  `266`
        // Estimated: `5080`
        // Minimum execution time: 13_000 nanoseconds.
        Weight::from_parts(14_000_000, 5080)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: Crowdfunding Campaigns (r:1 w:0)
    /// Storage: Crowdfunding CampaignWhitelist (r:1 w:1)
    /// Storage: Crowdfunding CampaignWhitelistCount (r:1 w:1)
    fn add_to_whitelist() -> Weight {
        // Measured:  `262`
        // Estimated: `12103`
        // Minimum execution time: 13_000 nanoseconds.
        Weight::from_parts(14_000_000, 12103)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    /// Storage: Crowdfunding Campaigns (r:1 w:0)
    /// Storage: Crowdfunding CampaignWhitelist (r:1 w:1)
    /// Storage: Crowdfunding CampaignWhitelistCount (r:1 w:1)
    fn remove_from_whitelist() -> Weight {
        // Measured:  `401`
        // Estimated: `12103`
        // Minimum execution time: 15_000 nanoseconds.
        Weight::from_parts(16_000_000, 12103)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    /// Storage: Crowdfunding ProtocolFeeRecipientOverride (r:0 w:1)
    /// Storage: Crowdfunding ProtocolFeeBpsOverride (r:0 w:1)
    fn set_protocol_config() -> Weight {
        // Measured:  `0`
        // Estimated: `0`
        // Minimum execution time: 8_000 nanoseconds.
        Weight::from_parts(9_000_000, 0)
            .saturating_add(T::DbWeight::get().writes(2))
    }

    /// Storage: Crowdfunding Campaigns (r:1 w:1)
    /// Storage: Rwa RwaAssets (r:1 w:0)
    /// Storage: Crowdfunding CampaignWhitelistCount (r:0 w:1)
    fn report_license_revoked() -> Weight {
        // Measured:  `276`
        // Estimated: `8964`
        // Minimum execution time: 23_000 nanoseconds.
        Weight::from_parts(23_000_000, 8964)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
}

/// Fallback weights for testing / development.
impl WeightInfo for () {
    fn create_campaign() -> Weight {
        Weight::from_parts(42_000_000, 12684)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(4))
    }

    fn cancel_campaign() -> Weight {
        Weight::from_parts(17_000_000, 5080)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(2))
    }

    fn set_default_eligibility() -> Weight {
        Weight::from_parts(8_000_000, 0)
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    fn invest() -> Weight {
        Weight::from_parts(43_000_000, 18555)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(5))
    }

    fn withdraw_investment() -> Weight {
        Weight::from_parts(50_000_000, 14841)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(4))
    }

    fn claim_refund() -> Weight {
        Weight::from_parts(42_000_000, 18555)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(5))
    }

    fn finalize_campaign() -> Weight {
        Weight::from_parts(15_000_000, 5080)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    fn claim_funds() -> Weight {
        Weight::from_parts(61_000_000, 12793)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(3))
    }

    fn claim_creation_deposit() -> Weight {
        Weight::from_parts(42_000_000, 12267)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(4))
    }

    fn submit_milestone() -> Weight {
        Weight::from_parts(17_000_000, 8583)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    fn approve_milestone() -> Weight {
        Weight::from_parts(17_000_000, 8583)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    fn reject_milestone() -> Weight {
        Weight::from_parts(17_000_000, 8583)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    fn claim_milestone_funds() -> Weight {
        Weight::from_parts(72_000_000, 18809)
            .saturating_add(RocksDbWeight::get().reads(6))
            .saturating_add(RocksDbWeight::get().writes(4))
    }

    fn pause_campaign() -> Weight {
        Weight::from_parts(14_000_000, 5080)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    fn resume_campaign() -> Weight {
        Weight::from_parts(14_000_000, 5080)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    fn add_to_whitelist() -> Weight {
        Weight::from_parts(14_000_000, 12103)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(2))
    }

    fn remove_from_whitelist() -> Weight {
        Weight::from_parts(16_000_000, 12103)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(2))
    }

    fn set_protocol_config() -> Weight {
        Weight::from_parts(9_000_000, 0)
            .saturating_add(RocksDbWeight::get().writes(2))
    }

    fn report_license_revoked() -> Weight {
        Weight::from_parts(23_000_000, 8964)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
}
