name: Lint

on:
  push:
    branches:
      - main
      - develop
      - release/*
      - hotfix/*
      - feature/*
      - ci/*

  pull_request:

env:
  CI: 1
  NIX_CONFIG: "experimental-features = nix-command flakes"

jobs:
  format:
    name: Lint format
    runs-on: [self-hosted, hetzner-thxnet]
    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y xz-utils

      - name: Ensure Nix is available
        run: |
          if [ -e /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]; then
            . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
            echo "/nix/var/nix/profiles/default/bin" >> "$GITHUB_PATH"
            echo "$HOME/.nix-profile/bin" >> "$GITHUB_PATH"
            sudo systemctl restart nix-daemon.service nix-daemon.socket || true
          fi

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install nixpkgs-fmt
        run: nix profile install 'nixpkgs#nixpkgs-fmt'

      - name: Run shfmt, shellcheck, checkbashisms
        uses: luizm/action-sh-checker@v0.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sh_checker_comment: true
          sh_checker_checkbashisms_enable: true

      - name: Run nixpkgs-fmt
        run: |
          nixpkgs-fmt --check .

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run prettier
        uses: creyD/prettier_action@v4.3
        with:
          dry: true
          prettier_options: --check **/*.{css,html,js,json,jsx,md,mdx,scss,ts,yaml}

  commit:
    name: Lint commit
    runs-on: [self-hosted, hetzner-thxnet]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run commitlint
        uses: wagoid/commitlint-github-action@v5.4.1
        with:
          firstParent: false

  codespell:
    name: Codespell
    runs-on: [self-hosted, hetzner-thxnet]
    steps:
      - uses: actions/checkout@v3

      - uses: codespell-project/codespell-problem-matcher@v1

      - name: Codespell
        uses: codespell-project/actions-codespell@master
