name: "Nix Flakes"

on:
  push:
    branches:
      - main
      - develop
      - ci/*
      - feat/*
      - feature/*
      - hotfix/*
      - release/*

  pull_request:

env:
  NIX_CONFIG: "experimental-features = nix-command flakes"

jobs:
  build-nix-flake:
    name: Build Nix Flake
    runs-on: hetzner-thxnet
    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y xz-utils

      - name: Prepare Nix cache directory
        run: |
          sudo mkdir -p "$HOME/.cache"
          sudo chown -R "$(id -u):$(id -g)" "$HOME/.cache"

      - name: Ensure Nix is available
        run: |
          if [ -e /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]; then
            . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
            echo "/nix/var/nix/profiles/default/bin" >> "$GITHUB_PATH"
            echo "$HOME/.nix-profile/bin" >> "$GITHUB_PATH"
            sudo systemctl restart nix-daemon.service nix-daemon.socket || true
          fi

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Build Nix Flake
        run: nix build

      - name: Test executable
        run: ./result/bin/thxnet-leafchain --version
