name: Release

on:
  push:
    tags:
      - "v*"
      - "nightly-*"

defaults:
  run:
    shell: bash

jobs:
  all:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v22

      - name: Pre Cache
        run: |
          rm -rf ~/.cargo/registry/index/ ~/.cargo/registry/cache/ ~/.cargo/git/db/

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build WASM runtimes
        run: |
          nix develop --command bash -c "WASM_TARGET_DIRECTORY=$(pwd) cargo build --release --package general-runtime"
          mv general_runtime.wasm general-runtime.wasm

      - name: Publish WASM runtimes
        uses: softprops/action-gh-release@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          draft: false
          prerelease: false
          files: |
            general-runtime.wasm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
