name: Release

on:
  push:
    tags:
      - "v*"
      - "nightly-*"

defaults:
  run:
    shell: bash

env:
  NIX_CONFIG: "experimental-features = nix-command flakes"
  RUSTC_WRAPPER: sccache
  SCCACHE_BUCKET: sccache
  SCCACHE_ENDPOINT: ${{ secrets.SCCACHE_ENDPOINT }}
  SCCACHE_S3_USE_SSL: "true"
  SCCACHE_REGION: auto
  AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_ACCESS_KEY }}

jobs:
  all:
    name: Release
    runs-on: [hetzner]
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Pre Cache
        run: |
          rm -rf ~/.cargo/registry/index/ ~/.cargo/registry/cache/ ~/.cargo/git/db/

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Show sccache version
        run: |
          nix develop --command sccache --version

      - name: Build WASM runtimes
        run: |
          nix develop --command bash -c "WASM_TARGET_DIRECTORY=$(pwd) cargo build --release --package general-runtime"
          mv general_runtime.wasm general-runtime.wasm

      - name: Show sccache stats
        run: |
          nix develop --command sccache --show-stats

      - name: Publish WASM runtimes
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          draft: false
          prerelease: false
          files: |
            general-runtime.wasm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
